name: release

on:
  release:
    types: [prereleased, released]

jobs:
  upload-helm-charts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: azure/setup-helm@v1
      
      - name: Package helm charts
        run: for dir in ./*/; do helm package $dir; done
        working-directory: deploy/charts/
        
      - name: Rename helm chart archives
        run: for filename in *.tgz; do mv "$filename" "helm-chart-$filename"; done;
        working-directory: deploy/charts/

      - uses: softprops/action-gh-release@v1
        with:
          files: deploy/charts/*.tgz
