name: release

on:
  release:
    types: [prereleased, released]

jobs:
  upload-helm-charts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: azure/setup-helm@v1
      
      - name: Package helm charts
        run: for dir in deploy/charts/*/; do helm package $dir -d deploy/charts/; done
        
      - name: Rename helm chart archives
        run: for filename in deploy/charts/*.tgz; do mv "$filename" "helm-chart-$filename"; done;
        
      - uses: softprops/action-gh-release@v1
        with:
          files: deploy/charts/*.tgz
